Week 01
maxzoladz/CS50 pull request #1
Opened 2024-08-01 14:56 UTC by maxzoladz

2024-08-01 15:06 UTC, luisthieme reviewed
Stell mal bei deinem Prettier ein das der EOF automatisch macht und dann geh nochmal durch alle dateien und lass die (durch speichern) formatieren

2024-08-01 15:10 UTC, luisthieme requested changes

2024-08-01 15:10 UTC, luisthieme commented on 01/mario-more/mario.c
> +   {
Das würde prettier auch wider fixen mit der richtigen einstellung aber kannst du dich generell dran gewöhnen: Hier bei 5minds schreiben alle die "{" in die Zeile wo zB das for(condition) steht

2024-08-01 15:10 UTC, luisthieme commented on 01/mario-more/mario.c
> +   {
```suggestion
   for(int i = 0; i < n; i++) {
```

2024-08-01 15:10 UTC, luisthieme commented on 01/me/hello.c
> +    char name[30];
Was wenn mein name länger als 30 Zeichen ist?

2024-08-02 06:56 UTC, maxzoladz commented on 01/me/hello.c
> +    char name[30];
Unfall

2024-08-02 11:38 UTC, luisthieme requested changes

2024-08-02 11:38 UTC, luisthieme commented on 01/cash/cash.c
> +int main(void){
```suggestion
int main(void) {
```

2024-08-02 11:38 UTC, luisthieme commented on 01/cash/cash.c
> +int main(void){
So bitte überall

2024-08-02 11:38 UTC, luisthieme commented on 01/cash/cash.c
> +}
EOF

2024-08-02 11:38 UTC, luisthieme commented on 01/credit/credit.c
> +    long long int length = floor(log10(llabs(cardNumberInt))) + 1;
Die Länge braucht keinen long long int ist ja nicht größer als zwei milliarden
```suggestion
    int length = floor(log10(llabs(cardNumberInt))) + 1;
```

2024-08-02 11:38 UTC, luisthieme commented on 01/credit/credit.c
> +}
EOF

2024-08-02 11:38 UTC, luisthieme commented on 01/helloWorld/hello.c
> +}
EOF

2024-08-02 11:44 UTC, LouisaStrunk02 commented on 01/cash/cash.c
> +int main(void){
Sollte auch mit prettier eingestellt werden können, damit die gesamte Datei on save automatisch formatiert wird.

2024-08-02 11:46 UTC, LouisaStrunk02 reviewed
Rechts unter Reviewer kannst du dich noch als Assignee eintragen

2024-08-02 11:48 UTC, luisthieme approved these changes

2024-08-02 11:53 UTC, LouisaStrunk02 commented on 01/cash/cash.c
> +    }
Das auch bei den anderen while-Schleifen

2024-08-02 12:06 UTC, LouisaStrunk02 approved these changes

2024-08-02 12:06 UTC, merged